# SPDX-FileCopyrightText: 2026 Dr Marcus Baw and Baw Medical Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 1
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
